dbt_airflow:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 10.159.19.121 #[hostname]
      user: postgres #[username]
      password: changeme #[password]
      port: 5431 #[port]
      dbname: dbt_airflow #[database name] # or database instead of dbname
      schema: public #[dbt schema]
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections
    
    prod: 
      